FROM mcr.microsoft.com/devcontainers/base:alpine
RUN apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing go golangci-lint
